name: Michael Tank
favicon: null
layout_spectrum: 0.45114
typography_spectrum: 0.88324
title: Michael Tank
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-3195758-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffe5be'
    - '#180f06'
    - '#d0ac72'
    - '#d4650c'
    - '#6a3e21'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.9375
  rhythmicContrast: 0.879300159169361
purpose: []
