name: michaeltank
favicon: null
layout_spectrum: 0.29422
typography_spectrum: 0.2350752742495388
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Michael Tank
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-3195758-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffe8c3'
    - '#1f1205'
    - '#f47600'
    - '#a3704d'
    - '#de2400'
  brandStrength: 0.125
  lightness: 0.125
  saturation: 0.75
  rhythmicContrast: 0.879300159169361
purpose: []
