name: michaeltank
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2350752742495388
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a6c3ff'
    - '#101010'
    - '#4d5673'
    - '#806e4a'
    - '#1246ac'
  brandStrength: 0.25
  lightness: 0.3125
  saturation: 0.8125
  rhythmicContrast: 0.879300159169361
purpose: []
