name: michaeltank
favicon: null
layout_spectrum: 0.59143
typography_spectrum: 0.2350752742495388
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: Michael Tank
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-3195758-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#251d12'
    - '#6b808b'
    - '#46575f'
    - '#e3ae6e'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.125
  rhythmicContrast: 0.879300159169361
purpose: []
